# Mathematics for Artificial Intelligence

## Lecture1. What is Vector?

### Vector
: 숫자를 원소로 가지는 list or array  

- 공간에서 한 점을 나타냄  

    ex) 1차원 => 수직선에 놓여있는 한 점  
    ex) 2차원 => 좌표평면에 놓여있는 한 점  
    ex) n차원 => n개의 좌표평면에 놓여있는 한 점  


- 벡터는 원점으로부터 상대적 위치를 표현  
=> 화살표 모양  

- 벡터의 숫자를 곱해주면 길이만 변함  
=> 이때 이것을 스칼라 곱이라 부름  
    - 1보다 크면 길이 증가
    - 1보다 작으면 길이 감소
    - But, 0 보다 작으면 반대 방향이 됨  






In [1]:
import numpy as np

# 행 벡터
x = [1, 7, 2]
x

[1, 7, 2]

In [3]:
# 행 벡터
x = np.array([1, 7, 2])
x

array([1, 7, 2])

### 벡터의 차원
: 벡터안의 숫자의 개수

### 벡터의 계산

벡터끼리 같은 모양을 가지면 덧셈, 뺄셈 계산 가능  

벡터끼리 같은 모양을 가지면 성분곱(Hadamard product) 계산 가능  

두 벡터의 덧셈은 다른 벡터로부터 상대적 이동을 표현

In [6]:
x = np.array([1,7,2])
y = np.array([5,2,1])

In [7]:
x + y

array([6, 9, 3])

In [8]:
x - y

array([-4,  5,  1])

In [9]:
x * y

array([ 5, 14,  2])

### 벡터의 노름
: 원점에서부터의 거리

- || . || 기호 : 노름
- ⛔ 임의의 차원 d에 대해 성립

### L1
: 각 성분의 변화량의 절대값을 모두 더함

$|| X ||_1 = \sum_{i=1}^d |x_i|$


### L2
: 피타고라스 정리를 이용해 유클리드 거리를 계산

-  ```np.linalg.norm 을 이용해도 구현 가능 ``` 

$|| X ||_2 = \sqrt{\sum_{i=1}^d |x_i|^2}$

x = [x1, x2, ... xd]

In [11]:
def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

In [12]:
def l2_norm(x):
    x_norm = x * x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

### Why L1, L2 다르게 정의?

- 노름의 종류에 따라 기하학적 성질이 달라짐
- 머신 러닝에서는 각 성질들이 필요할 때가 있으므로 둘 다 사용

![difference](https://ifh.cc/g/CMK8mb.png)


### 두 벡터 사이의 거리
- L1, L2 노름을 이용해 두 벡터 사이의 거리 계산 가능
- 두 벡터 사이의 거리를 계산할 때는 벡터의 뺄셈을 이용
- 뺄셈을 거꾸로 해도 거리는 동일

![distance](https://ifh.cc/g/MTow5k.png)


### 두 벡터 사이의 각도
⚠ L2노름만 사용 가능!

- 제 2 코사인 법칙에 의해 두 벡터 사이의 각도 계산 가능
- 내적을 이용해서 분자 쉽게 계산 가능

![cos](https://ifh.cc/g/WzZAcW.png)  
![cos1](https://ifh.cc/g/BsHQsW.png)

#### 내적 공식
- np.inner 이용해서 계산 

<x, y> = $\sum_{i=1}^d x_i y_i$

In [14]:
def angle(x,y):
    v = np.inner(x,y)/(l2_norm(x) * l2_norm(y))
    # 역 cos
    theta = np.arccos(v)
    return theta

### 내적

- 내적은 정사영(orthogonal projection)된 벡터의 길이와 관련
- Proj(x)의 길이는 코사인 법칙에 의해 $||X||cos\theta$


![proj](https://ifh.cc/g/MKfcdf.png)

Proj(x) : 벡터 y로 정사영된 벡터 x의 그림자


내적은 정사영의 길이를 벡터 y의  길이 ||y||만큼 조정한 값
- 내적은 두 벡터의 유사도(similarity)를 측정하는데 사용 가능

![proj1](https://ifh.cc/g/Jx2X0J.png)

## 행렬
: 벡터를 원소로 가지는 2차원 배열

- 행(row)과 열(column)이라는 인덱스를 가짐
    - X = ($x_{ij}$)
- numpy에서는 행(row)이 기본 단위
- 행렬의 특정 행(열)을 고정하면 행(열)벡터라 부름

In [15]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])